[app]
name = "go_gin"
port = 80
version = "1.0.0"
mode = "debug"

[mysql]
type = "mysql"
link = "root:123456@tcp(localhost:3306)/test"
charset = "utf8mb4"
maxIdle = 10
maxOpen = 100
maxLifetime = "30s"

[redis]
host = "127.0.0.1:6379"
password = "123456"
db = 0

[logger]
fileName = "./runtime/logs/a.log"
maxSize = 1
maxBackups = 30
maxAges = 7
compress = true
level = "debug"
